/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.vass.ejer.serviceBuilderListClient.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.vass.ejer.serviceBuilderListClient.model.persona;
import com.liferay.vass.ejer.serviceBuilderListClient.model.personaModel;
import com.liferay.vass.ejer.serviceBuilderListClient.model.personaSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the persona service. Represents a row in the &quot;VASS_persona&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>personaModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link personaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see personaImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class personaModelImpl
	extends BaseModelImpl<persona> implements personaModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a persona model instance should use the <code>persona</code> interface instead.
	 */
	public static final String TABLE_NAME = "VASS_persona";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"customerId", Types.INTEGER},
		{"storeId", Types.INTEGER}, {"firstName", Types.VARCHAR},
		{"lastName", Types.VARCHAR}, {"email", Types.VARCHAR},
		{"addressId", Types.INTEGER}, {"activebool", Types.VARCHAR},
		{"createDate", Types.VARCHAR}, {"lastUpdate", Types.VARCHAR},
		{"active_", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("customerId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("storeId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("firstName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("addressId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("activebool", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastUpdate", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("active_", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table VASS_persona (uuid_ VARCHAR(75) null,customerId INTEGER not null primary key,storeId INTEGER,firstName VARCHAR(75) null,lastName VARCHAR(75) null,email VARCHAR(75) null,addressId INTEGER,activebool VARCHAR(75) null,createDate VARCHAR(75) null,lastUpdate VARCHAR(75) null,active_ VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table VASS_persona";

	public static final String ORDER_BY_JPQL =
		" ORDER BY persona.customerId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY VASS_persona.customerId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long UUID_COLUMN_BITMASK = 1L;

	public static final long CUSTOMERID_COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static persona toModel(personaSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		persona model = new personaImpl();

		model.setUuid(soapModel.getUuid());
		model.setCustomerId(soapModel.getCustomerId());
		model.setStoreId(soapModel.getStoreId());
		model.setFirstName(soapModel.getFirstName());
		model.setLastName(soapModel.getLastName());
		model.setEmail(soapModel.getEmail());
		model.setAddressId(soapModel.getAddressId());
		model.setActivebool(soapModel.getActivebool());
		model.setCreateDate(soapModel.getCreateDate());
		model.setLastUpdate(soapModel.getLastUpdate());
		model.setActive(soapModel.getActive());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<persona> toModels(personaSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<persona> models = new ArrayList<persona>(soapModels.length);

		for (personaSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public personaModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _customerId;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setCustomerId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _customerId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return persona.class;
	}

	@Override
	public String getModelClassName() {
		return persona.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<persona, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<persona, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<persona, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((persona)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<persona, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<persona, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(persona)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<persona, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<persona, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, persona>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			persona.class.getClassLoader(), persona.class, ModelWrapper.class);

		try {
			Constructor<persona> constructor =
				(Constructor<persona>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<persona, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<persona, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<persona, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<persona, Object>>();
		Map<String, BiConsumer<persona, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<persona, ?>>();

		attributeGetterFunctions.put("uuid", persona::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<persona, String>)persona::setUuid);
		attributeGetterFunctions.put("customerId", persona::getCustomerId);
		attributeSetterBiConsumers.put(
			"customerId", (BiConsumer<persona, Integer>)persona::setCustomerId);
		attributeGetterFunctions.put("storeId", persona::getStoreId);
		attributeSetterBiConsumers.put(
			"storeId", (BiConsumer<persona, Integer>)persona::setStoreId);
		attributeGetterFunctions.put("firstName", persona::getFirstName);
		attributeSetterBiConsumers.put(
			"firstName", (BiConsumer<persona, String>)persona::setFirstName);
		attributeGetterFunctions.put("lastName", persona::getLastName);
		attributeSetterBiConsumers.put(
			"lastName", (BiConsumer<persona, String>)persona::setLastName);
		attributeGetterFunctions.put("email", persona::getEmail);
		attributeSetterBiConsumers.put(
			"email", (BiConsumer<persona, String>)persona::setEmail);
		attributeGetterFunctions.put("addressId", persona::getAddressId);
		attributeSetterBiConsumers.put(
			"addressId", (BiConsumer<persona, Integer>)persona::setAddressId);
		attributeGetterFunctions.put("activebool", persona::getActivebool);
		attributeSetterBiConsumers.put(
			"activebool", (BiConsumer<persona, String>)persona::setActivebool);
		attributeGetterFunctions.put("createDate", persona::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<persona, String>)persona::setCreateDate);
		attributeGetterFunctions.put("lastUpdate", persona::getLastUpdate);
		attributeSetterBiConsumers.put(
			"lastUpdate", (BiConsumer<persona, String>)persona::setLastUpdate);
		attributeGetterFunctions.put("active", persona::getActive);
		attributeSetterBiConsumers.put(
			"active", (BiConsumer<persona, String>)persona::setActive);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public int getCustomerId() {
		return _customerId;
	}

	@Override
	public void setCustomerId(int customerId) {
		_customerId = customerId;
	}

	@JSON
	@Override
	public int getStoreId() {
		return _storeId;
	}

	@Override
	public void setStoreId(int storeId) {
		_storeId = storeId;
	}

	@JSON
	@Override
	public String getFirstName() {
		if (_firstName == null) {
			return "";
		}
		else {
			return _firstName;
		}
	}

	@Override
	public void setFirstName(String firstName) {
		_firstName = firstName;
	}

	@JSON
	@Override
	public String getLastName() {
		if (_lastName == null) {
			return "";
		}
		else {
			return _lastName;
		}
	}

	@Override
	public void setLastName(String lastName) {
		_lastName = lastName;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		_email = email;
	}

	@JSON
	@Override
	public int getAddressId() {
		return _addressId;
	}

	@Override
	public void setAddressId(int addressId) {
		_addressId = addressId;
	}

	@JSON
	@Override
	public String getActivebool() {
		if (_activebool == null) {
			return "";
		}
		else {
			return _activebool;
		}
	}

	@Override
	public void setActivebool(String activebool) {
		_activebool = activebool;
	}

	@JSON
	@Override
	public String getCreateDate() {
		if (_createDate == null) {
			return "";
		}
		else {
			return _createDate;
		}
	}

	@Override
	public void setCreateDate(String createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public String getLastUpdate() {
		if (_lastUpdate == null) {
			return "";
		}
		else {
			return _lastUpdate;
		}
	}

	@Override
	public void setLastUpdate(String lastUpdate) {
		_lastUpdate = lastUpdate;
	}

	@JSON
	@Override
	public String getActive() {
		if (_active == null) {
			return "";
		}
		else {
			return _active;
		}
	}

	@Override
	public void setActive(String active) {
		_active = active;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public persona toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = _escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		personaImpl personaImpl = new personaImpl();

		personaImpl.setUuid(getUuid());
		personaImpl.setCustomerId(getCustomerId());
		personaImpl.setStoreId(getStoreId());
		personaImpl.setFirstName(getFirstName());
		personaImpl.setLastName(getLastName());
		personaImpl.setEmail(getEmail());
		personaImpl.setAddressId(getAddressId());
		personaImpl.setActivebool(getActivebool());
		personaImpl.setCreateDate(getCreateDate());
		personaImpl.setLastUpdate(getLastUpdate());
		personaImpl.setActive(getActive());

		personaImpl.resetOriginalValues();

		return personaImpl;
	}

	@Override
	public int compareTo(persona persona) {
		int primaryKey = persona.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof persona)) {
			return false;
		}

		persona persona = (persona)obj;

		int primaryKey = persona.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		personaModelImpl personaModelImpl = this;

		personaModelImpl._originalUuid = personaModelImpl._uuid;

		personaModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<persona> toCacheModel() {
		personaCacheModel personaCacheModel = new personaCacheModel();

		personaCacheModel.uuid = getUuid();

		String uuid = personaCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			personaCacheModel.uuid = null;
		}

		personaCacheModel.customerId = getCustomerId();

		personaCacheModel.storeId = getStoreId();

		personaCacheModel.firstName = getFirstName();

		String firstName = personaCacheModel.firstName;

		if ((firstName != null) && (firstName.length() == 0)) {
			personaCacheModel.firstName = null;
		}

		personaCacheModel.lastName = getLastName();

		String lastName = personaCacheModel.lastName;

		if ((lastName != null) && (lastName.length() == 0)) {
			personaCacheModel.lastName = null;
		}

		personaCacheModel.email = getEmail();

		String email = personaCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			personaCacheModel.email = null;
		}

		personaCacheModel.addressId = getAddressId();

		personaCacheModel.activebool = getActivebool();

		String activebool = personaCacheModel.activebool;

		if ((activebool != null) && (activebool.length() == 0)) {
			personaCacheModel.activebool = null;
		}

		personaCacheModel.createDate = getCreateDate();

		String createDate = personaCacheModel.createDate;

		if ((createDate != null) && (createDate.length() == 0)) {
			personaCacheModel.createDate = null;
		}

		personaCacheModel.lastUpdate = getLastUpdate();

		String lastUpdate = personaCacheModel.lastUpdate;

		if ((lastUpdate != null) && (lastUpdate.length() == 0)) {
			personaCacheModel.lastUpdate = null;
		}

		personaCacheModel.active = getActive();

		String active = personaCacheModel.active;

		if ((active != null) && (active.length() == 0)) {
			personaCacheModel.active = null;
		}

		return personaCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<persona, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<persona, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<persona, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((persona)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<persona, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<persona, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<persona, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((persona)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final Function<InvocationHandler, persona>
		_escapedModelProxyProviderFunction = _getProxyProviderFunction();
	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private int _customerId;
	private int _storeId;
	private String _firstName;
	private String _lastName;
	private String _email;
	private int _addressId;
	private String _activebool;
	private String _createDate;
	private String _lastUpdate;
	private String _active;
	private long _columnBitmask;
	private persona _escapedModel;

}