/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.vass.ejer.serviceBuilderListClient.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the persona service. Represents a row in the &quot;VASS_persona&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.vass.ejer.serviceBuilderListClient.model.impl.personaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.vass.ejer.serviceBuilderListClient.model.impl.personaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see persona
 * @generated
 */
@ProviderType
public interface personaModel extends BaseModel<persona> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a persona model instance should use the {@link persona} interface instead.
	 */

	/**
	 * Returns the primary key of this persona.
	 *
	 * @return the primary key of this persona
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this persona.
	 *
	 * @param primaryKey the primary key of this persona
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the uuid of this persona.
	 *
	 * @return the uuid of this persona
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this persona.
	 *
	 * @param uuid the uuid of this persona
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the customer ID of this persona.
	 *
	 * @return the customer ID of this persona
	 */
	public int getCustomerId();

	/**
	 * Sets the customer ID of this persona.
	 *
	 * @param customerId the customer ID of this persona
	 */
	public void setCustomerId(int customerId);

	/**
	 * Returns the store ID of this persona.
	 *
	 * @return the store ID of this persona
	 */
	public int getStoreId();

	/**
	 * Sets the store ID of this persona.
	 *
	 * @param storeId the store ID of this persona
	 */
	public void setStoreId(int storeId);

	/**
	 * Returns the first name of this persona.
	 *
	 * @return the first name of this persona
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this persona.
	 *
	 * @param firstName the first name of this persona
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this persona.
	 *
	 * @return the last name of this persona
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this persona.
	 *
	 * @param lastName the last name of this persona
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the email of this persona.
	 *
	 * @return the email of this persona
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this persona.
	 *
	 * @param email the email of this persona
	 */
	public void setEmail(String email);

	/**
	 * Returns the address ID of this persona.
	 *
	 * @return the address ID of this persona
	 */
	public int getAddressId();

	/**
	 * Sets the address ID of this persona.
	 *
	 * @param addressId the address ID of this persona
	 */
	public void setAddressId(int addressId);

	/**
	 * Returns the activebool of this persona.
	 *
	 * @return the activebool of this persona
	 */
	@AutoEscape
	public String getActivebool();

	/**
	 * Sets the activebool of this persona.
	 *
	 * @param activebool the activebool of this persona
	 */
	public void setActivebool(String activebool);

	/**
	 * Returns the create date of this persona.
	 *
	 * @return the create date of this persona
	 */
	@AutoEscape
	public String getCreateDate();

	/**
	 * Sets the create date of this persona.
	 *
	 * @param createDate the create date of this persona
	 */
	public void setCreateDate(String createDate);

	/**
	 * Returns the last update of this persona.
	 *
	 * @return the last update of this persona
	 */
	@AutoEscape
	public String getLastUpdate();

	/**
	 * Sets the last update of this persona.
	 *
	 * @param lastUpdate the last update of this persona
	 */
	public void setLastUpdate(String lastUpdate);

	/**
	 * Returns the active of this persona.
	 *
	 * @return the active of this persona
	 */
	@AutoEscape
	public String getActive();

	/**
	 * Sets the active of this persona.
	 *
	 * @param active the active of this persona
	 */
	public void setActive(String active);

}